# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d665f9500477275523317977cd5cc298f5c4044fc20c266d43926427c0de5a0b6d7be19b083b1f24b87db06530eb177ae5cf9c5da1c370127601a61aa77aa4cb

test:
  secret_key_base: 568603a089c0e09cd619f94c55eaf5723dbcd653dc3a5a7c2d52b03d369ddb4076c25eeac64186d0abe06a621c708065e35b2f3811f2969515c8f280b44668ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
